version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-yarn-deps-{{ checksum "package.json" }}
      - run: yarn test:ci
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: ./coverage/lcov.info
          token: 4fadb460-fe84-45fd-b2fe-59fe1df6bf9d
